name: Build and push docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install -U handsdown
      - name: Build docs
        run: |
          bash ./scripts/docs.sh
      - name: Push docs if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EMAIL: bot@altitudenetworks.com
        run: |
          bash ./scripts/push_docs.sh
