name: Lint and test changes

on:
  push:
    paths-ignore:
      - "docs/**"
      - "dynamo_query/version.txt"
      - "CHANGELOG.md"
      - "README.md"

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: 3.8-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            3.8-pip-
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements-dev.txt
      - name: Install
        run: |
          python setup.py install
      - name: Lint
        run: |
          vulture dynamo_query vulture_whitelist.py
          mypy dynamo_query
          pylint dynamo_query

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ matrix.python-version }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ matrix.python-version }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements-dev.txt
      - name: Install
        run: |
          python setup.py install
      - name: Unit tests
        run: |
          pytest -m "not integration"
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8000
          cors: "*"
      - name: Integration tests
        run: |
          pytest -m "integration"
      - name: Send coverage report
        if: matrix.python-version == '3.8'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          pytest --cov-report=xml --cov=dynamo_query -m "not integration"
          codecov
