name: Update docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install -U handsdown
      - name: Build docs
        id: build
        run: |
          bash ./scripts/docs.sh
          HAS_CHANGES=`git diff --stat | grep docs`
          echo "${HAS_CHANGES}"
          echo "##[set-output name=has_changes;]$(echo ${HAS_CHANGES})"
      - name: Create Pull Request
        if: ${{ steps.build.outputs.has_changes }}
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: actions/update-docs-${{ GITHUB_REF }}
          commit-message: Auto update docs
