name: Update docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install -U handsdown
      - name: Build docs
        id: build
        run: |
          bash ./scripts/docs.sh
          HAS_CHANGES=`git diff --stat | grep docs`
          echo "${HAS_CHANGES}"
          echo "##[set-output name=has_changes;]$(echo ${HAS_CHANGES})"
          echo "##[set-output name=branch_name;]$(echo actions/update-docs-${GITHUB_REF})"
      - name: Create Pull Request
        id: cpr
        if: steps.build.outputs.has_changes
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.build.outputs.branch_name }}
          commit-message: Auto update docs
          labels: docs, automated pr
          title: "[Actions] Auto update docs"
          body: Auto-generated docs were updated to reflect latest changes.
      - name: Check outputs
        if: steps.build.outputs.has_changes
        run: |
          echo "Created a PR #${{ steps.cpr.outputs.pr_number }}"
