name: Lint and test changes

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pylint mypy pytest pytest-cov codecov vulture 'boto3_stubs[dynamodb,application-autoscaling]'
          python -m mypy_boto3
      - name: Install
        run: |
          python setup.py install
      - name: Lint
        run: |
          ./scripts/before_commit.sh
      # - name: Send coverage report
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   run: |
      #     PYTHON_VER=`python -V | grep -Po '\d+\.+\d+'`
      #     if [[ "$PYTHON_VER" == "3.8" ]]; then
      #       pytest --cov-report term --cov mypy_boto3_builder
      #       codecov
      #     fi
